- CHANGELOG.md
Preparing for release v0.0.2
None
> :books: Updated CHANGELOG for release v0.0.2

- .circleci/config.yml
- README.md
- example/Dockerfile
- example/build.json
- example/config.json
Updating to match recent build environment changes.
None
> :rocket: Updating to match recent build environment changes

- .circleci/config.yml
- CHANGELOG.md
- README.md
- example/Dockerfile
- example/build.json
- example/config.json
- example/rootfs/etc/fix-attrs.d/10-run
- example/rootfs/usr/bin/run.sh
- Moved run.sh into /usr/bin
- Moved correcting file permission from Dockerfile into S6
- Updated README.md
- Updates config.json with some extra parameters
- Added new Hass.io Docker labels
- Added example options to add-on
- Moved resulting image build name from build.json into CircleCI
- Locked down base image version
- Changed add-on version to 'dev'
#4
> Rewrite onto s6 and new base image

- .gitlab-ci.yml
- README.md
- Updates GitLab CI to build on native architectures.
- Removed the need for the Docker build-env
- Adds Docker manifest
> Updates GitLab CI for native builds

- example/rootfs/etc/fix-attrs.d/10-run
- example/rootfs/etc/fix-attrs.d/scripts
Fix permissions on scripts, must have missed this after the last change.  Also renamed to remove the numeric identifier.
Fixes #15
> 🚑Fix permissions on shell scripts

- .github/workflows/deploy.yaml
Add support for the `edge`, `beta` and `stable` channels/environments to the deployment CI
> Adjust deployment supporting all environments

- LICENSE.md
- README.md
- example/.README.j2
- example/DOCS.md
> Happy New Year

- README.md
Yeah, well, the feature list was not really correct anymore.
This PR adjusts it a little, so it isn't a lie anymore 😉
> Adjust README to be correct

- README.md
Add some additional features to the list shown in the README.
> Extend list of features in README

- example/Dockerfile
- example/build.json
Updates the add-on base image to 9.0.1
Release notes: <https://github.com/hassio-addons/addon-base/releases/tag/v9.0.1>
> Upgrade add-on base image to 9.0.1

- example/Dockerfile
- example/build.json
Upgrade add-on base image to 9.1.1
> Upgrade add-on base image to 9.1.1

- example/Dockerfile
- example/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2
> Upgrade add-on base image to 9.1.2

- example/Dockerfile
- example/build.json
Upgrades add-on base image to v9.1.7
> ⬆️ Upgrades add-on base image to v9.1.7

- example/Dockerfile
- example/build.json
Upgrades add-on base image to v9.2.2
> ⬆️ Upgrades add-on base image to v9.2.2

- example/Dockerfile
- example/build.json
Upgrades add-on base image to v10.0.0
Running Alpine Linux 3.14
> ⬆️ Upgrades add-on base image to v10.0.0

- example/Dockerfile
- example/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v10.0.1
> ⬆️ Upgrades add-on base image to v10.0.1

- example/DOCS.md
- example/Dockerfile
- example/build.yaml
Upgrades add-on base image to v10.2.0
> :arrow_up: Upgrades add-on base image to v10.2.0

- example/Dockerfile
- example/build.yaml
Upgrades add-on base image to 10.2.2
> ⬆️ Upgrades add-on base image to 10.2.2

- example/Dockerfile
- example/build.yaml
Upgrades add-on base image to 11.0.0
> ⬆️ Upgrades add-on base image to 11.0.0

- LICENSE.md
- README.md
- example/.README.j2
- example/DOCS.md
> :fireworks: Updates maintenance/license year to 2022

- example/Dockerfile
- example/build.yaml
Upgrades add-on base image to 11.0.1
> ⬆️ Upgrades add-on base image to 11.0.1

- README.md
- example/.README.j2
> (Describe the changes and rationale behind them)
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
> Use yaml instead of json for add-on files

- example/Dockerfile
- example/build.yaml
Upgrades add-on base image to 11.1.0
> ⬆️ Upgrades add-on base image to 11.1.0

- example/build.yaml
- example/config.yaml
Sign add-on with the Codenotary Community Attestation Service (CAS)
> Sign add-on with Codenotary Community Attestation Service (CAS)

- example/DOCS.md
> :books: Add My buttons to documentation

- example/DOCS.md
> Put my button on new line

- example/DOCS.md
> :books: Hotfix repository link

- example/DOCS.md
> :books: Use new My Home Assistant link format

- example/Dockerfile
- example/build.yaml
> ⬆️ Upgrades add-on base image to 12.2.2

- example/Dockerfile
- example/build.yaml
> ⬆️ Upgrades add-on base image to 13.0.0

- LICENSE.md
- README.md
- example/.README.j2
- example/DOCS.md
> :fireworks: Updates maintenance/license year to 2023

- example/Dockerfile
- example/build.yaml
> ⬆️ Upgrades add-on base image to 13.1.1

- example/Dockerfile
- example/build.yaml
> ⬆️ Upgrades add-on base image to 13.1.3

- .github/renovate.json
- README.md
- example/build.yaml
- example/config.yaml
> Drop support for armhf & i386

- LICENSE.md
- README.md
- example/.README.j2
- example/DOCS.md
> :fireworks: Updates maintenance/license year to 2024

- LICENSE.md
- README.md
- example/.README.j2
- example/DOCS.md
> :fireworks: Updates maintenance/license year to 2025
